[package]
name = "nitron"
version = "0.1.0"
edition = "2024"

[dependencies]
renderer = { path = "renderer" }
winit = "0.30.10"
glam = "0.30.3"
tobj = "4.0.3"
egui_winit_vulkano = "0.28.0"
image = "0.25.6"

[profile.dev]
opt-level = 1